import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import { Provider } from './provider';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  preload: true,
  style: 'normal',
  display: 'swap',
  adjustFontFallback: true,
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: process.env.customKey ?? 'WILT',
  description: 'Generated by Peixola',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.className} antialiased`}>
        <AppRouterCacheProvider>
          <Provider>
            {children}
            <ToastContainer />
          </Provider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
